### ISSUE TITLE
question: simulate gps history trace

### ISSUE THREAD

**Issue by c-nv-s** [cemrehancavdar/hyperleaflet#29]
If I had a webpage which was connected via websocket and kept adding new datapoints each minute, could this show the entire history connected with lines? Basically simulate a gps trace.

**Comment by cemrehancavdar** [comment]
Hi @c-nv-s, 
There is no direct way to do it. But implementing it is fairly simple. 

Hyperleaflet is tracking changes in data-hyperleaflet-source container. So all we need is just create lines.

````
  <div id="map">
      <div data-hyperleaflet-source>
          <div id="**ws-lines**"></div>
      </div>
  </div>
````

The  data-hyperleaflet-source can be nested so for simplicity i seperated lines from other.
````
  <script>
      const hyperleafletSource = document.querySelector("#ws-lines")
      var ws = new WebSocket("ws://localhost:8000/ws");
      let idCounter = 1 
      let lastCoords = null
      ws.onmessage = function (event) {
          const data = JSON.parse(event.data) 
          if (lastCoords) {
              hyperleafletSource.innerHTML += `
              <span
              data-id="${idCounter}"
              data-geometry-type="LineString"
              data-geometry="[[${lastCoords.lat},${lastCoords.lon}],[${data.lat},${data.lon}],[${lastCoords.lat},${lastCoords.lon}]]"
            ></span>            
              `
              idCounter += 1
          }
          lastCoords = data
      };
  </script>
````
After that it is just a custom code piece that listen ws after first point creates new line and adds to data source. 
Same code is in sample repo.
You can check it there.

[There is a ](https://github.com/cemrehancavdar/hyperleaflet-ws-sample/blob/36b5bca31c1fcb874b519d5558438f9442f9038b/templates/index.html#L19)

Also, if possible just moving line creating logic to backend and send html tags, you can use with https://htmx.org/extensions/web-sockets/

**Comment by c-nv-s** [comment]
thanks for this. yeah I'll be using htmx together with hyperscript :-)

**Comment by cemrehancavdar** [comment]
Nice, closing this issue 😍 

Feel free to ask anything. Hyperscript is great to work with in hyperleaflet btw 🪴
