### ISSUE TITLE
More events

### ISSUE THREAD

**Issue by gtramontina** [cemrehancavdar/hyperleaflet#34]
Hey there,

First of all, thank you for this library. Such a nice idea!

Do you have plans on forwarding more of leaflet’s events? I’m in need of `moveend` at the moment and, before I go ahead and submit a PR, I wanted to ask you what are your thoughts on this (whether you’re rethinking the approach to events).

Also, do you have any thoughts on emiting these events on the dom element itself as opposed, or in addition, to `window`. To me it seems to make more sense and would allow for a more straightforward usage of hyperscript directly on the `#map` element without needing to refer to `window`. Not to mentioned that, from other parts of the DOM, the events are emitted by the `map` and not `window`.

Anyway, let me know. Cheers!

**Comment by cemrehancavdar** [comment]
Hey @gtramontina,

I've _implemented_ map:moveend and map:movestart events with 0.4.5 🥳 
I've also started rewriting the code from scratch, ensuring minimal disruptions. This rewrite includes modifications to internal components, offering more configurability and support for plugins. 

I initially hesitated about forwarding events to the window, as it didn't align with my previous approach. Would you like to discuss event targeting and event handling further? Could you provide an example of how hyperleaflet should handle this? Could you give me a imaginary code sample if hyperleaflet works like it?

I'm considering options like using data-event-target="me" or configuring it to other elements like window, body, #some-id, or .some-class. What's your preference?

Additionally, I'm working on introducing a "config" feature to enable styling and event disabling, aiming for a customizable but lightweight experience.

**Comment by gtramontina** [comment]
Here's what I had in mind when I mentioned emitting the events to the dom elements to which the map is attached to. Imagine a situation where we have 2 maps on the same screen (not sure how realistic this is, though, but entertain the idea for a second—in fact, the 2 maps is only a way to try and make the example more explicit). 


```html
<div
	id="map1"
	data-center="[0,0]"
	data-zoom="16"
	data-reverse-order-all
	_="on move(detail) log 'from map 1', detail"
>

<!-- … -->

<div
	id="map2"
	data-center="[0,0]"
	data-zoom="16"
	data-reverse-order-all
	_="on move(detail) log 'from map 2', detail"
>

<!-- … -->
<script type="text/hyperscript">
	on move(detail) from #map1 log 'from observing map 1', detail
	on move(detail) from #map2 log 'from observing map 2', detail
</script>
```

It seems to me that, from a user of hyperleaflet's perspective, this would make things more maintainable/consistent. By using `from #map1` in other elements/scripts, for example, I known straight away that the events are related to `#map1`.

BTW, do you have an idea on when `0.4.5` would be released? At the moment I'm hacking a way of tapping into these events 😅.

**Comment by cemrehancavdar** [comment]
[0.4.5](https://www.unpkg.com/hyperleaflet@0.4.5/dist/hyperleaflet.js) is live! 
I've already created a patch to include "map:moveend" and "map:movestart." Feel free to give it a try.

I believe the next version, which will support configuration options, should address your use case. I'll continue to give it more thought and consideration.

Regarding the possibility of having two hyperleaflet maps, it won't be available in the next release, but it's something that's on my radar for future development.

**Comment by gtramontina** [comment]
Thanks for the new version. Very quick! 💪

Re: the example I gave, the core of it wasn’t related to multiple maps, but with emitting the events to the dom element itself. Perhaps a PR would help explain the idea?

Is there be a place to reach out for questions/suggestions (gh discussions) or would you prefer them via gh issues?

Feel free to close this issue, btw.

Cheers!

**Comment by cemrehancavdar** [comment]
Thanks to giving it a try! 🥳

Yeah for questions or ideas github discussions would be better place. 
For longer questions etc you could reach @cemrehancavdar at discord. 

Feel free to reach for anything 🪴🌍
